MB-38843: Make CI capable of compiling cgo
Change-Id: I97a492cdd9ae11f51f8f161f60e523b1d982d367
Reviewed-on: http://review.couchbase.org/c/eventing/+/127292
Well-Formed: Build Bot <build@couchbase.com>
Tested-by: Sriram Melkote <siri@couchbase.com>
Reviewed-by: Sriram Melkote <siri@couchbase.com>

diff --git a/tests/ci/dotest b/tests/ci/dotest
--- a/tests/ci/dotest
+++ b/tests/ci/dotest
@@ -59,6 +59,7 @@ stop_cluster() {
 
 collect_logs() {
   if [ "$phase" = "" ]; then phase=unknown; fi
+  cat $WORKSPACE/test.log >> $WORKSPACE/test-full.log
   tar -C $WORKSPACE --transform "s/^/logs-$phase-/" -uf $WORKSPACE/logs.tar ns_server/logs 1>/dev/null 2>&1
   tar -C $WORKSPACE --transform "s/^/logs-$phase-/" -uf $WORKSPACE/logs.tar testrunner/logs 1>/dev/null 2>&1
   tar -C $WORKSPACE --transform "s/^/logs-$phase-/" -uf $WORKSPACE/logs.tar test.log 1>/dev/null 2>&1
@@ -80,7 +81,7 @@ error_email() {
   touch ~/.cinotify
 
   if [ "$WATCHERS" = "" -o ! -f ~/.cicred ]; then return; fi
-  cat /var/www/eventing-current.html | \
+  echo "$1" | \
      sendemail -q \
        -s smtp.gmail.com \
        -o tls=yes \
@@ -96,7 +97,7 @@ error_exit() {
   echo "$2"
   collect_logs
   stop_cluster
-  error_email
+  error_email "Testing Failed: $1\n$2"
   exit 2
 }
 
@@ -104,7 +105,7 @@ error_exit() {
 echo "Started testing at `date +'%Y/%m/%d %H:%M:%S'`"
 echo "Testing mode: $MODE"
 stop_cluster
-rm -f $WORKSPACE/logs.tar.* $WORKSPACE/test.log $WORKSPACE/stats.log $WORKSPACE/run.log /tmp/core-*
+rm -f $WORKSPACE/logs.tar.* $WORKSPACE/test.log $WORKSPACE/test-full.log $WORKSPACE/stats.log $WORKSPACE/run.log /tmp/core-*
 > $WORKSPACE/test.log
 > $WORKSPACE/stats.log
 
@@ -118,9 +119,12 @@ perl -pi -e 's/num_files, 10/num_files, 50/' $WORKSPACE/install/etc/couchbase/st
 cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/
 gover="`grep -A20 'SET(GOVERSION ' CMakeLists.txt  | grep GOVERSION | head -1 | sed 's/^.*\([0-9]\.[0-9]*.[0-9]\).*$/\1/'`"
 mkdir -p "$WORKSPACE/go"
-export GOROOT=$HOME/.cbdepscache/exploded/x86_64/go-$gover/go
-export GOPATH=$WORKSPACE/go:$WORKSPACE/godeps:$WORKSPACE/goproj
-export PATH=$PATH:$GOROOT/bin
+export GOROOT="$HOME/.cbdepscache/exploded/x86_64/go-$gover/go"
+export GOPATH="$WORKSPACE/go:$WORKSPACE/godeps:$WORKSPACE/goproj"
+export PATH="$PATH:$GOROOT/bin"
+export LD_LIBRARY_PATH="$WORKSPACE/install/lib"
+export C_INCLUDE_PATH="$WORKSPACE/build/platform/include:$WORKSPACE/forestdb/include:$WORKSPACE/build/tlm/deps/curl.exploded/include:$WORKSPACE/sigar/include"
+export CGO_LDFLAGS="-L $WORKSPACE/install/lib"
 
 cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/tests/functional_tests
 $GOROOT/bin/go get -t ./... 1>/dev/null 2>&1
@@ -131,7 +135,7 @@ if [[ "$MODE" == *"$phase"* ]]; then
   echo "</pre><h4>${phase^} tests</h4><pre>"
   echo "`date +'%Y/%m/%d %H:%M:%S'` Started $phase"
   cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/tests/functional_tests
-  GOMAXPROCS=16 $GOROOT/bin/go test -timeout 4h -tags handler -v -args --statsfile=$WORKSPACE/stats.log 2>&1 | tee -a $WORKSPACE/test.log
+  GOMAXPROCS=16 STATSFILE=$WORKSPACE/stats.log $GOROOT/bin/go test -timeout 4h -tags handler -v 2>&1 | tee -a $WORKSPACE/test.log
   collect_logs
 fi
 
@@ -141,7 +145,7 @@ if [[ "$MODE" == *"$phase"* ]]; then
   echo "</pre><h4>${phase^} tests</h4><pre>"
   echo "`date +'%Y/%m/%d %H:%M:%S'` Started $phase"
   cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/tests/functional_tests
-  GOMAXPROCS=16 $GOROOT/bin/go test -timeout 2h -tags n1ql -v -args --statsfile=$WORKSPACE/stats.log 2>&1 | tee -a $WORKSPACE/test.log
+  GOMAXPROCS=16 STATSFILE=$WORKSPACE/stats.log $GOROOT/bin/go test -timeout 2h -tags n1ql -v 2>&1 | tee -a $WORKSPACE/test.log
   collect_logs
 fi
 
@@ -151,7 +155,7 @@ if [[ "$MODE" == *"$phase"* ]]; then
   echo "</pre><h4>${phase^} tests</h4><pre>"
   echo "`date +'%Y/%m/%d %H:%M:%S'` Started $phase"
   cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/tests/functional_tests
-  GOMAXPROCS=16 $GOROOT/bin/go test -timeout 4h -tags curl -v -args --statsfile=$WORKSPACE/stats.log 2>&1 | tee -a $WORKSPACE/test.log
+  GOMAXPROCS=16 STATSFILE=$WORKSPACE/stats.log $GOROOT/bin/go test -timeout 4h -tags curl -v 2>&1 | tee -a $WORKSPACE/test.log
   collect_logs
 fi
 
@@ -165,7 +169,7 @@ if [[ "$MODE" == *"$phase"* ]]; then
   echo "</pre><h4>${phase^} tests</h4><pre>"
   echo "`date +'%Y/%m/%d %H:%M:%S'` Started $phase"
   cd $WORKSPACE/goproj/src/github.com/couchbase/eventing/tests/functional_tests
-  GOMAXPROCS=16 $GOROOT/bin/go test -timeout 24h -tags "eventing_reb testrunner_reb kv_reb duplicate_events" -v -args --statsfile=$WORKSPACE/stats.log 2>&1 | tee -a $WORKSPACE/test.log
+  GOMAXPROCS=16 STATSFILE=$WORKSPACE/stats.log $GOROOT/bin/go test -timeout 24h -tags "eventing_reb testrunner_reb kv_reb duplicate_events" -v 2>&1 | tee -a $WORKSPACE/test.log
   collect_logs
 fi
 
@@ -182,34 +186,35 @@ if [[ "$MODE" == *"$phase"* ]]; then
   collect_logs
 fi
 
+# Check to make sure N1QL grammer did not change recently
+cd $WORKSPACE/goproj/src/github.com/couchbase/query/parser/n1ql
+git ls-files -s n1ql.nex n1ql.y > ~/n1ql_parser.maybe
+test -f ~/n1ql_parser.good || cp ~/n1ql_parser.maybe ~/n1ql_parser.good
+msg="--- FAIL: N1QL grammer appears to have changed recently. Review and if OK, run: cp ~/n1ql_parser.maybe ~/n1ql_parser.good"
+diff ~/n1ql_parser.good ~/n1ql_parser.maybe || echo "$msg" >> /tmp/fail.log
+
 # Verify results
 > /tmp/fail.log
 cd $WORKSPACE/goproj/src/github.com/couchbase/eventing
-grep 'make:\s\*\*\*\s\[eventing-integration-tests\]\s' $WORKSPACE/test.log >> /tmp/fail.log
-grep '\sfail\s*$' $WORKSPACE/test.log >> /tmp/fail.log
-grep 'FAIL\s*github.com/couchbase' $WORKSPACE/test.log >> /tmp/fail.log
-grep -- '--- FAIL:' $WORKSPACE/test.log >> /tmp/fail.log
-grep '^\s*2i' $WORKSPACE/test.log | grep 'fail\s*$' >> /tmp/fail.log
+grep 'make:\s\*\*\*\s\[eventing-integration-tests\]\s' $WORKSPACE/test-full.log >> /tmp/fail.log
+grep '\sfail\s*$' $WORKSPACE/test-full.log >> /tmp/fail.log
+grep 'FAIL\s*github.com/couchbase' $WORKSPACE/test-full.log >> /tmp/fail.log
+grep -- '--- FAIL:' $WORKSPACE/test-full.log >> /tmp/fail.log
+grep '^\s*2i' $WORKSPACE/test-full.log | grep 'fail\s*$' >> /tmp/fail.log
+egrep 'pass [0-9]+.*fail [1-9]+' $WORKSPACE/test-full.log >> /tmp/fail.log
 faillog="`cat /tmp/fail.log`"
 if [ "$faillog" != "" ]; then error_exit "Required test failed" "$faillog"; fi
 echo "</pre><h4>Testing Succeeded</h4><pre>"
 echo
 
-cd $WORKSPACE
-cat ~/repos.list | while read line ; do
-   repo=`echo $line | awk '{print $1}'`
-   loc=`echo $line | awk '{print $2}'`
-   cd $loc
-   git rev-parse HEAD > ~/$repo.good
+cd ~
+for file in *.maybe; do
+    mv "$file" "$(basename "$file" .maybe).good"
 done
 
-if [ "$CIBOT" = "true" ]; then
-  cd $WORKSPACE/goproj/src/github.com/couchbase/eventing
-  git rev-parse couchbase/$BRANCH > ~/eventing.good
-  for patch_id in `cat ~/gerrit.list`; do
-    ssh review.couchbase.org gerrit review --code-review 1 -m "'PASS $MODE. See https://$CINAME.northscale.in/eventing-$TS.pass.html'" $patch_id
-  done
-fi
+for patch_id in `cat ~/gerrit.list`; do
+  ssh review.couchbase.org gerrit review --code-review 1 -m "'PASS $MODE. See https://$CINAME.northscale.in/eventing-$TS.pass.html'" $patch_id
+done
 
 touch ~/.cigreen
 exit 0
