MB-100: Skip N1QL grammar change check in CI
* Likely any grammar changes will get caught in the CI N1QL
  tests

Change-Id: I6535044ce03a272531a0c827253592a37cd6fdaf
Reviewed-on: http://review.couchbase.org/c/eventing/+/145023
Tested-by: Vinayaka Kamath <vinayaka.kamath@couchbase.com>
Reviewed-by: Vinayaka Kamath <vinayaka.kamath@couchbase.com>

diff --git a/tests/ci/dotest b/tests/ci/dotest
--- a/tests/ci/dotest
+++ b/tests/ci/dotest
@@ -191,11 +191,12 @@ if [[ "$MODE" == *"$phase"* ]]; then
 fi
 
 # Check to make sure N1QL grammer did not change recently
-cd $WORKSPACE/goproj/src/github.com/couchbase/query/parser/n1ql
-git ls-files -s n1ql.nex n1ql.y > ~/n1ql_parser.maybe
-test -f ~/n1ql_parser.good || cp ~/n1ql_parser.maybe ~/n1ql_parser.good
-msg="FAIL(manual): N1QL grammer appears to have changed recently. Review and if OK, run: cp ~/n1ql_parser.maybe ~/n1ql_parser.good"
-diff -q ~/n1ql_parser.good ~/n1ql_parser.maybe || echo "$msg" >> $WORKSPACE/test-full.log
+# TODO: automate this check instead of skipping it
+# cd $WORKSPACE/goproj/src/github.com/couchbase/query/parser/n1ql
+# git ls-files -s n1ql.nex n1ql.y > ~/n1ql_parser.maybe
+# test -f ~/n1ql_parser.good || cp ~/n1ql_parser.maybe ~/n1ql_parser.good
+# msg="FAIL(manual): N1QL grammer appears to have changed recently. Review and if OK, run: cp ~/n1ql_parser.maybe ~/n1ql_parser.good"
+# diff -q ~/n1ql_parser.good ~/n1ql_parser.maybe || echo "$msg" >> $WORKSPACE/test-full.log
 
 # Verify results
 > /tmp/fail.log
